main:methods.c
	gcc -o methods methods.c `pkg-config --cflags opencv` `pkg-config --libs opencv`


main:getHist.c
	gcc -o getHist getHist.c `pkg-config --cflags opencv` `pkg-config --libs opencv`

main:getContour.c
	gcc -o getContour getContour.c `pkg-config --cflags opencv` `pkg-config --libs opencv`
